### ISSUE TITLE
AttributeError: 'int' object has no attribute 'isdigit'

### ISSUE THREAD

**Issue by kroman0** [openprocurement/openprocurement.bot.identification#16]
```
Traceback (most recent call last):
  File "/home/edr_bot_dev/openprocurement.bridge.buildout/eggs/gevent-1.1.1-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/edr_bot_dev/openprocurement.bridge.buildout/src/openprocurement.bot.identification/openprocurement/bot/identification/databridge/edr_handler.py", line 63, in get_edr_id
    response = self.proxyClient.verify(validate_param(tender_data.code), tender_data.code)
  File "/home/edr_bot_dev/openprocurement.bridge.buildout/src/openprocurement.bot.identification/openprocurement/bot/identification/databridge/utils.py", line 31, in validate_param
    return 'id' if code.isdigit() and len(code) != id_passport_len else 'passport'
AttributeError: 'int' object has no attribute 'isdigit'
<Greenlet at 0x7f9b31d929b0: <bound method EdrHandler.get_edr_id of <EdrHandler at 0x7f9b346c5730>>> failed with AttributeError
```

**Comment by IrynaPomazan** [comment]
В [документації ](http://api-docs.openprocurement.org/uk_UA/latest/standard/organization.html#identifier) зазначено, що поле "id" - string. Воно може бути типу int?

**Comment by kroman0** [comment]
Не мало б.
Але є https://lb.api-sandbox.openprocurement.org/api/dev/tenders/24870b4dff454743976023753f76e267
