### ISSUE TITLE
KeyError in upload_to_tender

### ISSUE THREAD

**Issue by kroman0** [openprocurement/openprocurement.bot.identification#22]
```
Traceback (most recent call last):
  File "/home/edr_bot_dev/openprocurement.bridge.buildout/eggs/gevent-1.1.1-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/edr_bot_dev/openprocurement.bridge.buildout/src/openprocurement.bot.identification/openprocurement/bot/identification/databridge/upload_file.py", line 146, in upload_to_tender
    del self.processing_items[tender_data.item_id]
KeyError: '5e146019572645718c92bac1857250fa'
<Greenlet at 0x7fe6b31db0f0: <bound method UploadFile.upload_to_tender of <UploadFile at 0x7fe6b41be7d0>>> failed with KeyError
```
Якщо потрібна додаткова інформація то пишіть.

**Comment by IrynaPomazan** [comment]
Так, якщо можна, цікавить більше логів саме по цьому тендеру.
