### ISSUE TITLE
Обробка помилок при роботі з ЦБД

### ISSUE THREAD

**Issue by kroman0** [openprocurement/openprocurement.bot.identification#25]
Наразі безперервно отримуємо такі помилки
```
2017-04-04 15:53:25,175 - openprocurement.bot.identification.databridge.upload_file - INFO - Exception while retry uploading file to tender 1bff14a21f3f4e7c99b86da58f87771f awards 9a3d1ae6554f4ce694b30d51c143509c. Message: {"status": "error", "errors": [{"location": "body", "name": "lots", "description": [{"auctionPeriod": {"startDate": ["period should begin before its end"]}}]}]}
2017-04-04 15:53:25,176 - openprocurement.bot.identification.databridge.upload_file - ERROR - {"status": "error", "errors": [{"location": "body", "name": "lots", "description": [{"auctionPeriod": {"startDate": ["period should begin before its end"]}}]}]}
Traceback (most recent call last):
  File "/home/edr_bot_dev/openprocurement.bridge.buildout/src/openprocurement.bot.identification/openprocurement/bot/identification/databridge/upload_file.py", line 155, in retry_upload_to_tender
    self.client_upload_to_tender(tender_data)
  File "/home/edr_bot_dev/openprocurement.bridge.buildout/eggs/retrying-1.3.3-py2.7.egg/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/edr_bot_dev/openprocurement.bridge.buildout/eggs/retrying-1.3.3-py2.7.egg/retrying.py", line 212, in call
    raise attempt.get()
  File "/home/edr_bot_dev/openprocurement.bridge.buildout/eggs/retrying-1.3.3-py2.7.egg/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/edr_bot_dev/openprocurement.bridge.buildout/eggs/retrying-1.3.3-py2.7.egg/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/edr_bot_dev/openprocurement.bridge.buildout/src/openprocurement.bot.identification/openprocurement/bot/identification/databridge/upload_file.py", line 180, in client_upload_to_tender
    tender_data.item_id))
  File "/home/edr_bot_dev/openprocurement.bridge.buildout/eggs/openprocurement_client-1.0b2-py2.7.egg/openprocurement_client/client.py", line 220, in _create_tender_resource_item
    getattr(getattr(tender, 'access', ''), 'token', '')}
  File "/home/edr_bot_dev/openprocurement.bridge.buildout/eggs/openprocurement_client-1.0b2-py2.7.egg/openprocurement_client/client.py", line 103, in _create_resource_item
    url, headers=headers, payload=dumps(payload)
  File "/home/edr_bot_dev/openprocurement.bridge.buildout/eggs/restkit-4.2.2-py2.7.egg/restkit/resource.py", line 144, in post
    headers=headers, params_dict=params_dict, **params)
  File "/home/edr_bot_dev/openprocurement.bridge.buildout/eggs/openprocurement_client-1.0b2-py2.7.egg/openprocurement_client/client.py", line 62, in request
    params_dict=params_dict, **params
  File "/home/edr_bot_dev/openprocurement.bridge.buildout/eggs/restkit-4.2.2-py2.7.egg/restkit/resource.py", line 210, in request
    response=resp)
RequestFailed: {"status": "error", "errors": [{"location": "body", "name": "lots", "description": [{"auctionPeriod": {"startDate": ["period should begin before its end"]}}]}]}
```

**Comment by IrynaPomazan** [comment]
В даному тендері https://lb.api-sandbox.openprocurement.org/api/dev/tenders/1bff14a21f3f4e7c99b86da58f87771f маємо ситуацію коли auctionPeriod.startDate більший за endDate. Що робити з такими тендерами?

**Comment by kroman0** [comment]
У випадку виникнення таких помилок(з кодом 422) найдоцільніше логувати проблему і пропускати.
