### ISSUE TITLE
KeyError in update_processing_items

### ISSUE THREAD

**Issue by kroman0** [openprocurement/openprocurement.bot.identification#70]
```
2017-06-07 15:14:29,113 - openprocurement.bot.identification.databridge.upload_file - WARNING - retry_upload_to_tender worker dead try restart
2017-06-07 15:14:29,113 - openprocurement.bot.identification.databridge.upload_file - INFO - retry_upload_to_tender worker is up
2017-06-07 15:14:29,166 - openprocurement.bot.identification.databridge.upload_file - WARNING - retry_upload_to_tender worker dead try restart
2017-06-07 15:14:29,166 - openprocurement.bot.identification.databridge.upload_file - INFO - retry_upload_to_tender worker is up
2017-06-07 15:14:29,667 - openprocurement.bot.identification.databridge.upload_file - WARNING - retry_upload_to_tender worker dead try restart
2017-06-07 15:14:29,667 - openprocurement.bot.identification.databridge.upload_file - INFO - retry_upload_to_tender worker is up
2017-06-07 15:14:29,813 - openprocurement.bot.identification.databridge.upload_file - WARNING - retry_upload_to_tender worker dead try restart
2017-06-07 15:14:29,814 - openprocurement.bot.identification.databridge.upload_file - INFO - retry_upload_to_tender worker is up
```
```
Traceback (most recent call last):
  File "/home/edr_bot/openprocurement.bridge.buildout/eggs/gevent-1.1.1-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/edr_bot/openprocurement.bridge.buildout/src/openprocurement.bot.identification/openprocurement/bot/identification/databridge/upload_file.py", line 251, in retry_upload_to_tender
    self.update_processing_items(tender_data.tender_id, tender_data.item_id)
  File "/home/edr_bot/openprocurement.bridge.buildout/src/openprocurement.bot.identification/openprocurement/bot/identification/databridge/upload_file.py", line 268, in update_processing_items
    if self.processing_items[key] > 1:
KeyError: '8fb4eb905b26472eb8c71e2a7e538fa6_be8b1fa2467a4732af48712008cb696b'
<Greenlet at 0x7ffb1c186c30: <bound method UploadFile.retry_upload_to_tender of <UploadFile at 0x7ffb1d66e5f0>>> failed with KeyError

Traceback (most recent call last):
  File "/home/edr_bot/openprocurement.bridge.buildout/eggs/gevent-1.1.1-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/edr_bot/openprocurement.bridge.buildout/src/openprocurement.bot.identification/openprocurement/bot/identification/databridge/upload_file.py", line 251, in retry_upload_to_tender
    self.update_processing_items(tender_data.tender_id, tender_data.item_id)
  File "/home/edr_bot/openprocurement.bridge.buildout/src/openprocurement.bot.identification/openprocurement/bot/identification/databridge/upload_file.py", line 268, in update_processing_items
    if self.processing_items[key] > 1:
KeyError: 'f273383bd1554add80e80ac757e332eb_8c44d41a2d3d4992aace7f35289b0e75'
<Greenlet at 0x7ffb1c21e4b0: <bound method UploadFile.retry_upload_to_tender of <UploadFile at 0x7ffb24098230>>> failed with KeyError
```

**Comment by ZVasyl** [comment]
@Mexicanec , please comment on majority as well
