### ISSUE TITLE
Опрацювання 429 помилки в запитах до ЦБД

### ISSUE THREAD

**Issue by kroman0** [openprocurement/openprocurement.bot.identification#74]
```
Traceback (most recent call last):
  File "/home/edr_bot_24/openprocurement.bridge.buildout/src/openprocurement.bot.identification/openprocurement/bot/identification/databridge/scanner.py", line 115, in get_tenders_backward
    for tender in self.get_tenders(params=params, direction="backward"):
  File "/home/edr_bot_24/openprocurement.bridge.buildout/src/openprocurement.bot.identification/openprocurement/bot/identification/databridge/scanner.py", line 65, in get_tenders
    response = self.initialize_sync(params=params, direction=direction)
  File "/home/edr_bot_24/openprocurement.bridge.buildout/eggs/retrying-1.3.3-py2.7.egg/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/edr_bot_24/openprocurement.bridge.buildout/eggs/retrying-1.3.3-py2.7.egg/retrying.py", line 212, in call
    raise attempt.get()
  File "/home/edr_bot_24/openprocurement.bridge.buildout/eggs/retrying-1.3.3-py2.7.egg/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/edr_bot_24/openprocurement.bridge.buildout/eggs/retrying-1.3.3-py2.7.egg/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/edr_bot_24/openprocurement.bridge.buildout/src/openprocurement.bot.identification/openprocurement/bot/identification/databridge/scanner.py", line 50, in initialize_sync
    response = self.tenders_sync_client.sync_tenders(params, extra_headers={'X-Client-Request-ID': generate_req_id()})
  File "/home/edr_bot_24/openprocurement.bridge.buildout/eggs/openprocurement_client-1.0b2-py2.7.egg/openprocurement_client/client.py", line 559, in sync_tenders
    response = self.get(self.prefix_path, params_dict=params)
  File "/home/edr_bot_24/openprocurement.bridge.buildout/eggs/restkit-4.2.2-py2.7.egg/restkit/resource.py", line 114, in get
    params_dict=params_dict, **params)
  File "/home/edr_bot_24/openprocurement.bridge.buildout/eggs/openprocurement_client-1.0b2-py2.7.egg/openprocurement_client/client.py", line 62, in request
    params_dict=params_dict, **params
  File "/home/edr_bot_24/openprocurement.bridge.buildout/eggs/restkit-4.2.2-py2.7.egg/restkit/resource.py", line 210, in request
    response=resp)
RequestFailed: {'msg': '', 'status_int': 429, 'response': <restkit.wrappers.Response object at 0x7f2e77fad150>}

Traceback (most recent call last):
  File "/home/edr_bot_24/openprocurement.bridge.buildout/src/openprocurement.bot.identification/openprocurement/bot/identification/databridge/scanner.py", line 115, in get_tenders_backward
    for tender in self.get_tenders(params=params, direction="backward"):
  File "/home/edr_bot_24/openprocurement.bridge.buildout/src/openprocurement.bot.identification/openprocurement/bot/identification/databridge/scanner.py", line 92, in get_tenders
    raise re
RequestFailed: {'msg': '', 'status_int': 429, 'response': <restkit.wrappers.Response object at 0x7f2e7c508110>}
```

**Comment by kroman0** [comment]
Окрім scanner помилки можуть виникати і в filter_tender і в upload_file
