### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by kroman0** [openprocurement/openprocurement.bot.identification#78]
```
Traceback (most recent call last):
  File "/home/edr_bot/openprocurement.bridge.buildout/eggs/gevent-1.1.1-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/edr_bot/openprocurement.bridge.buildout/src/openprocurement.bot.identification/openprocurement/bot/identification/databridge/edr_handler.py", line 266, in retry_get_edr_details
    tender_data.tender_id, tender_data.item_name, tender_data.item_id, document_id, re.args[1].json().get('errors')),
  File "/home/edr_bot/openprocurement.bridge.buildout/eggs/requests-2.10.0-py2.7.egg/requests/models.py", line 812, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/edr_bot/openprocurement.bridge.buildout/eggs/simplejson-3.6.5-py2.7-linux-x86_64.egg/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/home/edr_bot/openprocurement.bridge.buildout/eggs/simplejson-3.6.5-py2.7-linux-x86_64.egg/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/edr_bot/openprocurement.bridge.buildout/eggs/simplejson-3.6.5-py2.7-linux-x86_64.egg/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
<Greenlet at 0x7fbd17a52730: <bound method EdrHandler.retry_get_edr_details of <EdrHandler at 0x7fbd17a52230>>> failed with JSONDecodeError

Traceback (most recent call last):
  File "/home/edr_bot/openprocurement.bridge.buildout/eggs/gevent-1.1.1-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/edr_bot/openprocurement.bridge.buildout/src/openprocurement.bot.identification/openprocurement/bot/identification/databridge/edr_handler.py", line 266, in retry_get_edr_details
    tender_data.tender_id, tender_data.item_name, tender_data.item_id, document_id, re.args[1].json().get('errors')),
  File "/home/edr_bot/openprocurement.bridge.buildout/eggs/requests-2.10.0-py2.7.egg/requests/models.py", line 812, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/edr_bot/openprocurement.bridge.buildout/eggs/simplejson-3.6.5-py2.7-linux-x86_64.egg/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/home/edr_bot/openprocurement.bridge.buildout/eggs/simplejson-3.6.5-py2.7-linux-x86_64.egg/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/edr_bot/openprocurement.bridge.buildout/eggs/simplejson-3.6.5-py2.7-linux-x86_64.egg/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
<Greenlet at 0x7fbd167f04b0: <bound method EdrHandler.retry_get_edr_details of <EdrHandler at 0x7fbd17a52230>>> failed with JSONDecodeError
```

**Comment by ZVasyl** [comment]
Is it blocker for PROD or not? @kroman? @myroslav?
